### Importing the packages or initialization

In [1]:
import numpy as np
import os
raw_dataset_path = '/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data'

In [2]:
np.set_printoptions(suppress=True, linewidth=100, precision=2)

### Importing the Data

In [3]:
import chardet
with open(os.path.join(raw_dataset_path, 'raw/loan-data.csv'), 'rb') as loan_dataset:
    result = chardet.detect(loan_dataset.read(200000))
    print(result)

{'encoding': 'windows-1251', 'confidence': 0.8953878210175097, 'language': 'Bulgarian'}


In [4]:
# loan_raw_data = np.loadtxt(os.path.join(raw_dataset_path, 'raw/loan-data.csv'), # Error due to missing values
#                            delimiter=";",
#                           encoding='windows-1251') 
raw_loan_data = np.genfromtxt(os.path.join(raw_dataset_path, 'raw/loan-data.csv'), 
                              delimiter=";",
                             encoding='windows-1251',
                             skip_header=True,
                             autostrip=True)
raw_loan_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]],
      shape=(10000, 14))

In [5]:
raw_loan_data.shape

(10000, 14)

### Checking for Incomplete Data

In [6]:
np.isnan(raw_loan_data).sum()

np.int64(88005)

In [7]:
temporary_fill = np.nanmax(raw_loan_data) + 1
temporary_mean = np.nanmean(raw_loan_data, axis=0)

/var/folders/jx/cc9brgl143z9wt4bc65wylz40000gn/T/ipykernel_26575/1082398316.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_loan_data, axis=0)


In [8]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [9]:
temporary_stats = np.array([np.nanmin(raw_loan_data, axis=0),
                           temporary_mean,
                           np.nanmax(raw_loan_data, axis=0)])

/var/folders/jx/cc9brgl143z9wt4bc65wylz40000gn/T/ipykernel_26575/3048557867.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_loan_data, axis=0),
/var/folders/jx/cc9brgl143z9wt4bc65wylz40000gn/T/ipykernel_26575/3048557867.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_loan_data, axis=0)])


In [10]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

## Splitting the Dataset
### Splitting the column

In [11]:
column_strings = np.argwhere(np.isnan(temporary_mean))
column_strings

array([[ 1],
       [ 3],
       [ 5],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [12]:
np.isnan(temporary_mean)

array([False,  True, False,  True, False,  True, False, False,  True,  True,  True,  True,  True,
       False])

In [13]:
column_strings = np.argwhere(np.isnan(temporary_mean)).squeeze()
column_strings

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [14]:
column_number = np.argwhere(np.isnan(temporary_mean) == False).squeeze()
column_number

array([ 0,  2,  4,  6,  7, 13])

### Reimporting the Dataset

In [15]:
loan_data_string = np.genfromtxt(os.path.join(raw_dataset_path, 'raw/loan-data.csv'), 
                              delimiter=";",
                             encoding='windows-1251',
                             skip_header=True,
                             autostrip=True,
                             usecols=column_strings,
                                dtype=np.str_)
loan_data_string

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

In [16]:
loan_data_numeric = np.genfromtxt(os.path.join(raw_dataset_path, 'raw/loan-data.csv'), 
                              delimiter=";",
                             encoding='windows-1251',
                             skip_header=True,
                             autostrip=True,
                             usecols=column_number,
                             filling_values=temporary_fill)
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]],
      shape=(10000, 6))

### The names of the columns

In [17]:
header_full = np.genfromtxt(os.path.join(raw_dataset_path, 'raw/loan-data.csv'), 
                              delimiter=";",
                             encoding='windows-1251',
                            skip_footer=raw_loan_data.shape[0],
                           dtype=np.str_)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [18]:
header_for_string_loandata, header_for_numeric_loandata = header_full[column_strings], header_full[column_number]

In [19]:
header_for_numeric_loandata

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [20]:
header_for_string_loandata

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Creating Checkpoints

In [21]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    file_name = '/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/processed/' + file_name
    np.savez(file_name, header=checkpoint_header, data=checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return checkpoint_variable

In [22]:
checkpoint_test = checkpoint("checkpoint-test", header_for_string_loandata, loan_data_string)

In [23]:
checkpoint_test

NpzFile '/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/processed/checkpoint-test.npz' with keys: header, data

In [24]:
checkpoint_test['header']

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [25]:
checkpoint_test['data']

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

In [26]:
np.array_equal(checkpoint_test['data'], loan_data_string)

True

In [27]:
np.array_equal(checkpoint_test['header'], header_for_string_loandata)

True

### Manipulating the strings columns

In [28]:
header_for_string_loandata

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [29]:
header_for_string_loandata[0] = 'issue_date'

In [30]:
header_for_string_loandata

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Issue Date

In [31]:
loan_data_string[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], shape=(10000,), dtype='<U69')

In [32]:
np.unique(loan_data_string[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [33]:
np.char.strip(loan_data_string[:,0], "-15")

array(['May', '', 'Sep', ..., 'Jun', 'Apr', 'Dec'], shape=(10000,), dtype='<U69')

In [34]:
loan_data_string[:,0] = np.char.strip(loan_data_string[:,0], "-15")
loan_data_string

array([['May', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

In [35]:
months = np.array(['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'])

In [36]:
for i in range(13):
    loan_data_string[:,0] = np.where(loan_data_string[:,0] == months[i], 
                                     str(i), 
                                     loan_data_string[:,0])
loan_data_string

array([['5', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['0', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['9', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['6', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['4', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['12', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      shape=(10000, 8), dtype='<U69')

In [37]:
np.unique(loan_data_string[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Loan Status

In [38]:
header_for_string_loandata

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [39]:
loan_data_string[:,1]

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'],
      shape=(10000,), dtype='<U69')

In [40]:
np.unique(loan_data_string[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [41]:
status_bad = np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [42]:
loan_data_string[:,1] = np.where(np.isin(loan_data_string[:,1],status_bad), '0', '1')

In [43]:
np.unique(loan_data_string[:,1])

array(['0', '1'], dtype='<U69')

### Term

In [44]:
loan_data_string[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      shape=(10000,), dtype='<U69')

In [45]:
np.unique(loan_data_string[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [46]:
loan_data_string[:,2] = np.char.strip(loan_data_string[:,2], ' months')
loan_data_string[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], shape=(10000,), dtype='<U69')

In [47]:
header_for_string_loandata[2] = 'term_months'

In [48]:
header_for_string_loandata

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [49]:
loan_data_string[:,2] = np.where(loan_data_string[:,2] == '', '60', loan_data_string[:,2])

In [50]:
np.unique(loan_data_string[:,2])

array(['36', '60'], dtype='<U69')

### Grade and SubGrade

In [51]:
header_for_string_loandata

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [52]:
loan_data_string[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], shape=(10000,), dtype='<U69')

In [53]:
np.unique(loan_data_string[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [54]:
loan_data_string[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], shape=(10000,), dtype='<U69')

In [55]:
np.unique(loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [56]:
np.unique(loan_data_string[:,3])[1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [57]:
for i in np.unique(loan_data_string[:,3])[1:]:
    loan_data_string[:,4] = np.where((loan_data_string[:,4] == '') & (loan_data_string[:,3] == i), 
                                     str(i) + '5', 
                                    loan_data_string[:,4]) 

In [58]:
np.unique(loan_data_string[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [59]:
np.unique(loan_data_string[:,4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [60]:
# Fill the blank with the worst or new unique value
loan_data_string[:,4] = np.where(loan_data_string[:,4] == '', 'H1', loan_data_string[:,4])

In [61]:
np.unique(loan_data_string[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

### Removing Grade column (no use)

In [62]:
loan_data_string = np.delete(loan_data_string, 3, axis=1)

In [63]:
header_for_string_loandata = np.delete(header_for_string_loandata, 3)

In [64]:
header_for_string_loandata[3]

np.str_('sub_grade')

### Converting sub grade

In [65]:
keys = list(np.unique(loan_data_string[:,3]))

In [66]:
keys

[np.str_('A1'),
 np.str_('A2'),
 np.str_('A3'),
 np.str_('A4'),
 np.str_('A5'),
 np.str_('B1'),
 np.str_('B2'),
 np.str_('B3'),
 np.str_('B4'),
 np.str_('B5'),
 np.str_('C1'),
 np.str_('C2'),
 np.str_('C3'),
 np.str_('C4'),
 np.str_('C5'),
 np.str_('D1'),
 np.str_('D2'),
 np.str_('D3'),
 np.str_('D4'),
 np.str_('D5'),
 np.str_('E1'),
 np.str_('E2'),
 np.str_('E3'),
 np.str_('E4'),
 np.str_('E5'),
 np.str_('F1'),
 np.str_('F2'),
 np.str_('F3'),
 np.str_('F4'),
 np.str_('F5'),
 np.str_('G1'),
 np.str_('G2'),
 np.str_('G3'),
 np.str_('G4'),
 np.str_('G5'),
 np.str_('H1')]

In [67]:
values = list(range(1, np.unique(loan_data_string[:,3]).shape[0]+1))

In [68]:
values

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36]

In [69]:
dict_sub_grade = dict(zip(keys, values))
dict_sub_grade

{np.str_('A1'): 1,
 np.str_('A2'): 2,
 np.str_('A3'): 3,
 np.str_('A4'): 4,
 np.str_('A5'): 5,
 np.str_('B1'): 6,
 np.str_('B2'): 7,
 np.str_('B3'): 8,
 np.str_('B4'): 9,
 np.str_('B5'): 10,
 np.str_('C1'): 11,
 np.str_('C2'): 12,
 np.str_('C3'): 13,
 np.str_('C4'): 14,
 np.str_('C5'): 15,
 np.str_('D1'): 16,
 np.str_('D2'): 17,
 np.str_('D3'): 18,
 np.str_('D4'): 19,
 np.str_('D5'): 20,
 np.str_('E1'): 21,
 np.str_('E2'): 22,
 np.str_('E3'): 23,
 np.str_('E4'): 24,
 np.str_('E5'): 25,
 np.str_('F1'): 26,
 np.str_('F2'): 27,
 np.str_('F3'): 28,
 np.str_('F4'): 29,
 np.str_('F5'): 30,
 np.str_('G1'): 31,
 np.str_('G2'): 32,
 np.str_('G3'): 33,
 np.str_('G4'): 34,
 np.str_('G5'): 35,
 np.str_('H1'): 36}

In [70]:
for i in np.unique(loan_data_string[:,3]):
    loan_data_string[:,3] = np.where(loan_data_string[:,3] == i,
                                    str(dict_sub_grade[i]),
                                    loan_data_string[:,3])

In [71]:
loan_data_string[:,3]

array(['13', '5', '10', ..., '5', '17', '4'], shape=(10000,), dtype='<U69')

In [72]:
np.unique(loan_data_string[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

### Verification status

In [73]:
header_for_string_loandata

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [74]:
loan_data_string[:,4]

array(['Verified', 'Source Verified', 'Verified', ..., 'Source Verified', 'Source Verified', ''],
      shape=(10000,), dtype='<U69')

In [75]:
np.unique(loan_data_string[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [76]:
verification_bad = np.array(['', 'Not Verified'])
loan_data_string[:,4] = np.where(np.isin(loan_data_string[:,4], verification_bad), 0, 1)

In [77]:
loan_data_string[:,4]

array(['1', '1', '1', ..., '1', '1', '0'], shape=(10000,), dtype='<U69')

In [78]:
np.unique(loan_data_string[:,4])

array(['0', '1'], dtype='<U69')

### URL

In [79]:
loan_data_string[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'],
      shape=(10000,), dtype='<U69')

In [80]:
loan_data_string[:,5] = np.char.strip(loan_data_string[:,5], 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=')

In [81]:
loan_data_string[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
      shape=(10000,), dtype='<U69')

In [82]:
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [83]:
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.], shape=(10000,))

In [84]:
np.array_equal(loan_data_string[:,5].astype(np.int32), loan_data_numeric[:,0].astype(np.int32))

True

In [85]:
# URL column could be dropped no use
loan_data_string = np.delete(loan_data_string, 5, axis=1)
header_for_string_loandata = np.delete(header_for_string_loandata, 5)

In [86]:
loan_data_string

array([['5', '1', '36', '13', '1', 'CA'],
       ['0', '1', '36', '5', '1', 'NY'],
       ['9', '1', '36', '10', '1', 'PA'],
       ...,
       ['6', '1', '36', '5', '1', 'CA'],
       ['4', '1', '36', '17', '1', 'OH'],
       ['12', '1', '36', '4', '0', 'IL']], shape=(10000, 6), dtype='<U69')

In [87]:
loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], shape=(10000,), dtype='<U69')

### State Addr

In [88]:
header_for_string_loandata

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [89]:
loan_data_string[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], shape=(10000,), dtype='<U69')

In [90]:
np.unique(loan_data_string[:,5], return_counts=True)

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27]))

In [91]:
states_names, states_count = np.unique(loan_data_string[:,5], return_counts=True)
states_count_sorted = np.argsort(-states_count)
states_names[states_count_sorted], states_count[states_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10]))

In [92]:
loan_data_string[:,5] = np.where(loan_data_string[:,5] == '',
                                '0',
                                loan_data_string[:,5])

In [93]:
states_west = np.array(['WA', 'OR', 'CA', 'NV', 'ID', 'MT', 'WY', 'UT', 'CO', 'AZ', 'NM', 'HI', 'AK'])
states_south = np.array(['AL', 'TX', 'OK', 'AR', 'LA', 'MS', 'TN', 'KY', 'FL', 'GA', 'SC', 'NC', 'VA', 'WV', 'MD', 'DE', 'DC'])
states_midwest = np.array(['ND', 'SD', 'NE', 'KS', 'MN', 'IA', 'MO', 'WI', 'IL', 'IN', 'MI', 'OH'])
states_east = np.array(['PA', 'NY', 'NJ', 'CT', 'MA', 'VT', 'NH', 'ME', 'RI'])

In [94]:
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_west), '1', loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_south), '2', loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_midwest), '3', loan_data_string[:,5])
loan_data_string[:,5] = np.where(np.isin(loan_data_string[:,5], states_east), '4', loan_data_string[:,5])

In [95]:
np.unique(loan_data_string[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

### Converting Numbers

In [96]:
loan_data_string.astype(np.int32)

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], shape=(10000, 6), dtype=int32)

In [97]:
loan_data_string = loan_data_string.astype(np.int32)
loan_data_string

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], shape=(10000, 6), dtype=int32)

### Checkpoint 1: Strings

In [98]:
checkpoint_strings = checkpoint("Checkpoint-Strings", header_for_string_loandata, loan_data_string)

In [99]:
checkpoint_strings['header']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [100]:
checkpoint_strings['data']

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]], shape=(10000, 6), dtype=int32)

In [101]:
np.array_equal(checkpoint_strings['data'], loan_data_string)

True

## Manipulating Numeric Columns

In [102]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]],
      shape=(10000, 6))

In [103]:
np.isnan(loan_data_numeric).sum() ## the columns have temporary fill

np.int64(0)

### Substitute "Filler" Values

In [104]:
header_for_numeric_loandata

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ID

In [105]:
temporary_fill

np.float64(68616520.0)

In [106]:
np.isin(loan_data_numeric[:,0], temporary_fill)

array([False, False, False, ..., False, False, False], shape=(10000,))

In [107]:
np.isin(loan_data_numeric[:,0], temporary_fill).sum()

np.int64(0)

#### Temporary stats

In [108]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [109]:
column_number

array([ 0,  2,  4,  6,  7, 13])

In [110]:
temporary_stats[:, column_number]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### Funded Amount

In [111]:
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.], shape=(10000,))

In [112]:
loan_data_numeric[:,2] = np.where(loan_data_numeric[:,2] == temporary_fill,
                                 temporary_stats[0, column_number[2]],
                                 loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.], shape=(10000,))

#### Loaned Amount, Interest Rate, Total Payment, Installment

In [113]:
header_for_numeric_loandata

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [114]:
for i in [1,3,4,5]:
    loan_data_numeric[:,i] = np.where(loan_data_numeric[:,i] == temporary_fill,
                                     temporary_stats[2, column_number[i]],
                                     loan_data_numeric[:,i])

In [115]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]],
      shape=(10000, 6))

## Currency Change

### The Exchange Rate

In [116]:
EUR_USD = np.genfromtxt(os.path.join(raw_dataset_path, 'raw/EUR-USD.csv'), 
                        delimiter=',',
                       autostrip=True,
                       dtype=np.str_)
EUR_USD

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [117]:
EUR_USD = np.genfromtxt(os.path.join(raw_dataset_path, 'raw/EUR-USD.csv'), 
                       delimiter=',',
                       skip_header=True,
                       autostrip=True,
                       usecols=[3])
EUR_USD

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [118]:
loan_data_string[:,0]

array([ 5,  0,  9, ...,  6,  4, 12], shape=(10000,), dtype=int32)

In [119]:
header_for_string_loandata

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [120]:
exchange_rate = loan_data_string[:,0]
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i,
                            EUR_USD[i-1],
                            exchange_rate)
exchange_rate = np.where(exchange_rate == 0,
                        np.mean(EUR_USD),
                        exchange_rate)
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09], shape=(10000,))

In [121]:
exchange_rate.shape

(10000,)

In [122]:
loan_data_string.shape

(10000, 6)

In [123]:
exchange_rate = np.reshape(exchange_rate, (10000,1))
exchange_rate

array([[1.1 ],
       [1.11],
       [1.13],
       ...,
       [1.12],
       [1.11],
       [1.09]], shape=(10000, 1))

In [124]:
loan_data_numeric = np.hstack([loan_data_numeric, exchange_rate])
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]],
      shape=(10000, 7))

In [125]:
header_for_numeric_loandata = np.concatenate([header_for_numeric_loandata, np.array(['exchange_rate'])])

In [126]:
header_for_numeric_loandata

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### From USD to EUR

In [127]:
header_for_numeric_loandata

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [128]:
column_dollar = np.array([1,2,4,5])

In [129]:
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09], shape=(10000,))

In [130]:
for i in column_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, np.reshape(loan_data_numeric[:,i]/loan_data_numeric[:,6],
                                                               (10000,1))))

In [131]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]],
      shape=(10000, 11))

In [132]:
loan_data_numeric.shape

(10000, 11)

#### Expanding the header

In [133]:
header_additional = np.array([column_name + '_EUR' for column_name in header_for_numeric_loandata[column_dollar]])

In [134]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [135]:
header_for_numeric_loandata = np.concatenate((header_for_numeric_loandata, header_additional))

In [136]:
header_for_numeric_loandata

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [137]:
header_for_numeric_loandata[column_dollar] = np.array([column_name + '_USD' for column_name in header_for_numeric_loandata[column_dollar]])

In [138]:
header_for_numeric_loandata

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [139]:
column_index_order = [0,1,7,2,8,3,4,9,5,10,6] ## Rearranging the columns so that USD, EUR side by side

In [140]:
header_for_numeric_loandata = header_for_numeric_loandata[column_index_order]
header_for_numeric_loandata

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [141]:
loan_data_numeric = loan_data_numeric[:,column_index_order]

In [142]:
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]],
      shape=(10000, 11))

#### Interest Rate

In [143]:
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99], shape=(10000,))

In [144]:
loan_data_numeric[:,5] = loan_data_numeric[:,5]/100

In [145]:
loan_data_numeric[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29], shape=(10000,))

### Checkpoint 2: Numeric

In [146]:
checkpoint_numeric = checkpoint('Checkpoint-Numeric', header_for_numeric_loandata, loan_data_numeric)

In [147]:
checkpoint_numeric

NpzFile '/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/processed/Checkpoint-Numeric.npz' with keys: header, data

In [148]:
checkpoint_numeric['header'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]],
       shape=(10000, 11)))

### Creating the "Complete" Dataset

In [149]:
checkpoint_strings['data'].shape

(10000, 6)

In [150]:
checkpoint_numeric['data'].shape

(10000, 11)

In [151]:
loan_data = np.hstack([checkpoint_numeric['data'], checkpoint_strings['data']])

In [152]:
loan_data

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]],
      shape=(10000, 17))

In [153]:
np.isnan(loan_data).sum()

np.int64(0)

In [154]:
header_full = np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))

In [155]:
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

### Sorting the new dataset

In [156]:
## As per 1st column
loan_data[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.], shape=(10000,))

In [157]:
np.sort(loan_data[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.], shape=(10000,))

In [158]:
loan_data = loan_data[np.argsort(loan_data[:,0])]
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]],
      shape=(10000, 17))

### Storing the new dataset

In [161]:
loan_data = np.vstack((header_full, loan_data))

In [162]:
np.savetxt(os.path.join(raw_dataset_path, 'processed/loan-data-preprocessed.csv'), 
           loan_data, 
           fmt="%s", 
           delimiter=",")