# Generating Data w/ NumPy

In [1]:
import numpy as np

## np.empty(), np.zeros(), np.ones(), np.full()

In [2]:
# Functions that quickly generate arrays of data
array_empty = np.empty(shape = (2,3))
array_empty.dtype

dtype('float64')

In [3]:
array_zeros = np.zeros(shape = (2,3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
array_zeros = np.zeros(shape = (2,3), dtype = np.int8)
array_zeros

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [5]:
array_ones = np.ones(shape=(2,2), dtype='str')
array_ones

array([['1', '1'],
       ['1', '1']], dtype='<U1')

In [6]:
array_full = np.full(shape = (2,3), fill_value=2)
array_full

array([[2, 2, 2],
       [2, 2, 2]])

## _like functions

In [7]:
matrix_a = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_a

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [8]:
array_empty_like = np.empty_like(matrix_a)
array_empty_like

array([[                  0,                   0, 4607182418800017408,
        4589168020290535424, 4598175219545276416],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4617385886705778688],
       [4612248968380809216, 4607182418800017408, 4625196817309499392,
        4616189618054758400, 4607182418800017408]])

In [9]:
array_zeros_like = np.zeros_like(matrix_a)
array_zeros_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
array_ones_like = np.ones_like(matrix_a)
array_ones_like

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
array_full_like = np.full_like(matrix_a, fill_value=4)
array_full_like

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

## np.arange()

In [12]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [14]:
np.arange(stop=30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [15]:
np.arange(start=21, stop=30)

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [16]:
np.arange(start=21, stop=30, step=2.5)

array([21. , 23.5, 26. , 28.5])

In [17]:
np.arange(start=21, stop=30, step=2.5, dtype=np.float16)

array([21. , 23.5, 26. , 28.5], dtype=float16)

In [18]:
np.arange(start=21, stop=30, step=2.5, dtype=np.int32)

array([21, 23, 25, 27], dtype=int32)

## Random generators

### Defining Random Generators and seeds

In [19]:
from numpy.random import Generator as gen, PCG64 as pcg

In [20]:
array_random_generated = gen(pcg())
array_random_generated.normal()

0.6593229013310892

In [21]:
array_random_generated.normal(size = 5)

array([-0.93089652,  0.66358516,  0.01986127,  0.00137674, -0.49804319])

In [22]:
array_random_generated.normal(size=(5,5))

array([[-1.4128298 ,  1.09676593,  0.44627955,  0.18530277, -1.15059852],
       [-0.03599469,  1.36071175, -1.07301539,  0.92509764,  0.69836683],
       [-0.40816628, -0.4955468 , -2.11679666, -1.02424822,  0.41155035],
       [ 0.15767291, -0.49796673, -0.1244353 , -0.89539433,  0.09171336],
       [-1.64598627, -1.53874466,  0.53158668,  0.33976916, -2.8419843 ]])

In [23]:
array_random_generated = gen(pcg(seed=365))
array_random_generated.normal(size=(5,5))

array([[-0.13640899,  0.09414431, -0.06300442,  1.05391641, -0.6866818 ],
       [-0.50922173, -0.7999526 ,  0.73041825,  0.08825439, -2.1177576 ],
       [ 0.65526774, -0.48095012, -0.5519114 , -0.58578662, -0.98257896],
       [ 1.12378166, -1.30984316, -0.04703774,  0.955272  ,  0.26071745],
       [-0.20023668, -1.50172484, -1.4929163 ,  0.96535084,  1.18694633]])

## Generating Integers, Probabilities and Random Choices

In [24]:
array_random_generated = gen(pcg(seed=365))
array_random_generated.integers(4, size=(2,2))

array([[0, 3],
       [2, 3]])

In [25]:
array_random_generated = gen(pcg(seed=365))
array_random_generated.integers(low=10, high=100, size=(5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]])

In [26]:
array_random_generated = gen(pcg(seed=365))
array_random_generated.random(size=(5,5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [27]:
array_random_generated = gen(pcg(seed=365))
array_random_generated.choice([1,2,3,4,5], size=(5,5)) # Passed list value for choice

array([[1, 4, 4, 4, 5],
       [4, 4, 2, 1, 4],
       [2, 1, 2, 4, 5],
       [1, 1, 5, 4, 3],
       [3, 5, 4, 3, 5]])

In [28]:
array_random_generated = gen(pcg(seed=365))
array_random_generated.choice([1,2,3,4,5], p = [0.1, .2, .3, .2, .2], size=(5,5)) # Passed list value for choice + probability

array([[4, 4, 4, 2, 4],
       [1, 4, 2, 5, 3],
       [5, 3, 1, 4, 3],
       [2, 3, 3, 4, 3],
       [4, 1, 4, 5, 2]])

## Generating Arrays From Known Distributions

In [29]:
array_random_generated = gen(pcg(seed=365))
array_random_generated.poisson(size=(5,5))

array([[2, 0, 1, 1, 2],
       [1, 1, 0, 1, 1],
       [1, 2, 1, 1, 0],
       [0, 1, 0, 2, 1],
       [0, 1, 0, 0, 2]])

In [30]:
array_random_generated = gen(pcg(seed=365))
array_random_generated.poisson(lam =10, size=(5,5))

array([[11, 12, 12, 14, 13],
       [ 9, 10, 11, 11,  8],
       [11,  8, 10,  9, 14],
       [ 7,  8,  9, 15, 15],
       [13,  8,  8,  7,  9]])

In [31]:
array_random_generated = gen(pcg(seed=365))
array_random_generated.binomial(n=100, p=0.8, size=(5,5))

array([[77, 77, 79, 83, 78],
       [86, 78, 85, 75, 80],
       [76, 81, 86, 78, 81],
       [82, 80, 80, 79, 80],
       [79, 87, 78, 76, 84]])

In [32]:
array_random_generated = gen(pcg(seed=365))
array_random_generated.logistic(loc=9, scale=1.2, size=(5,5))

array([[10.37767822, 10.42451863,  9.63404367,  7.36153427,  9.82286787],
       [ 5.81223125, 10.09354231,  6.46790532, 11.38740256,  8.97147918],
       [10.85844698,  8.79081317,  5.962079  ,  9.99560681,  8.34539118],
       [ 7.97105522,  8.9981544 ,  8.93530194,  9.6253307 ,  9.23850869],
       [ 9.73729284,  5.3090678 , 10.13723528, 11.04372782,  7.11078651]])

## Application of Random Generators

In [33]:
array_random_generated = gen(pcg(seed=365))
array_column_1 = array_random_generated.normal(loc=2, scale=3, size=1000)
array_column_2 = array_random_generated.normal(loc=7, scale=2, size=1000)
array_column_3 = array_random_generated.logistic(loc=11, scale=3, size=1000)
array_column_4 = array_random_generated.exponential(scale=4, size=1000)
array_column_5 = array_random_generated.geometric(p=0.7, size=1000)

In [34]:
random_test_data = np.array([array_column_1, array_column_2, array_column_3, array_column_4, array_column_5])
random_test_data

array([[ 1.59077303,  2.28243293,  1.81098674, ...,  0.1973629 ,
        -2.21015722,  2.91161235],
       [ 6.42174295,  8.57902322,  5.17270135, ...,  4.3465854 ,
         8.2176402 ,  7.90337695],
       [10.14698427, 15.93309953, -0.46878789, ...,  2.66485989,
        12.69328115, 11.79840961],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         2.        ,  1.        ]], shape=(5, 1000))

In [35]:
random_test_data.shape

(5, 1000)

In [36]:
random_test_data.transpose()
random_test_data.shape

(5, 1000)

In [37]:
random_test_data

array([[ 1.59077303,  2.28243293,  1.81098674, ...,  0.1973629 ,
        -2.21015722,  2.91161235],
       [ 6.42174295,  8.57902322,  5.17270135, ...,  4.3465854 ,
         8.2176402 ,  7.90337695],
       [10.14698427, 15.93309953, -0.46878789, ...,  2.66485989,
        12.69328115, 11.79840961],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         2.        ,  1.        ]], shape=(5, 1000))

In [38]:
np.savetxt("Random-Test-from-NumPy.csv", random_test_data, fmt="%s", delimiter= ",")

In [39]:
np.genfromtxt("Random-Test-from-NumPy.csv", delimiter=",")

array([[ 1.59077303,  2.28243293,  1.81098674, ...,  0.1973629 ,
        -2.21015722,  2.91161235],
       [ 6.42174295,  8.57902322,  5.17270135, ...,  4.3465854 ,
         8.2176402 ,  7.90337695],
       [10.14698427, 15.93309953, -0.46878789, ...,  2.66485989,
        12.69328115, 11.79840961],
       [ 6.91500737,  6.243605  ,  2.44997251, ...,  0.80935387,
         0.50644607,  4.86816939],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         2.        ,  1.        ]], shape=(5, 1000))