## Importing Data with NumPy

In [1]:
import numpy as np

### np.loadtxt() vs np.genfromtxt()

In [6]:
lending_co_data_numeric_1 = np.loadtxt("/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/raw/Lending-Company-Numeric-Data.csv", delimiter=",")

In [3]:
lending_co_data_numeric_1

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [4]:
lending_co_data_numeric_2 = np.genfromtxt("/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/raw/Lending-Company-Numeric-Data.csv", delimiter=",")
lending_co_data_numeric_2

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [5]:
np.array_equal(lending_co_data_numeric_1, lending_co_data_numeric_2)

True

In [8]:
lending_co_data_numeric_NAN = np.loadtxt("/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/raw/Lending-Company-Numeric-Data-NAN.csv", delimiter=";")
lending_co_data_numeric_NAN

ValueError: could not convert string '' to float64 at row 11, column 4.

In [9]:
lending_co_data_numeric_NAN = np.genfromtxt("/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/raw/Lending-Company-Numeric-Data-NAN.csv", delimiter=";")
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

### Partial Cleaning While Importing

In [11]:
lending_co_data_numeric_NAN = np.genfromtxt
("/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/raw/Lending-Company-Numeric-Data-NAN.csv", 
 delimiter=";",
 skip_header=2)
lending_co_data_numeric_NAN

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1041, 6))

In [15]:
lending_co_data_numeric_NAN = np.genfromtxt("/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/raw/Lending-Company-Numeric-Data-NAN.csv", delimiter=";",
                                            skip_footer=2)
lending_co_data_numeric_NAN

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  3401.,    nan, 16600.],
       [ 2000.,    40.,   365.,    nan,  5440., 16600.],
       [   nan,    40.,   365.,  4201.,  5001., 16600.]], shape=(1041, 6))

In [17]:
lending_co_data_numeric_NAN = np.genfromtxt("/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/raw/Lending-Company-Numeric-Data-NAN.csv", delimiter=";",
                                            usecols=(5,0,1))
lending_co_data_numeric_NAN

array([[13621.,  2000.,    40.],
       [15041.,  2000.,    40.],
       [15340.,  1000.,    40.],
       ...,
       [16600.,    nan,    40.],
       [15600.,  1000.,    40.],
       [16600.,  2000.,    40.]], shape=(1043, 3))

In [18]:
lending_co_data_numeric_NAN = np.genfromtxt("/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/raw/Lending-Company-Numeric-Data-NAN.csv", delimiter=";",
                                            usecols=(5,0,1),
                                           skip_footer=2,
                                           skip_header=2)
lending_co_data_numeric_NAN

array([[15340.,  1000.,    40.],
       [15321.,  2000.,    40.],
       [13720.,  2000.,    50.],
       ...,
       [16600.,  2000.,    40.],
       [16600.,  2000.,    40.],
       [16600.,    nan,    40.]], shape=(1039, 3))

In [21]:
# Storing the o/p in different varibles
lending_1, lending_2, lending_3 = np.genfromtxt("/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/raw/Lending-Company-Numeric-Data-NAN.csv", delimiter=";",
                                            usecols=(5,0,1),
                                           skip_footer=2,
                                           skip_header=2,
                                           unpack=True)
print(lending_1)
print(lending_2)
print(lending_3)

[15340. 15321. 13720. ... 16600. 16600. 16600.]
[1000. 2000. 2000. ... 2000. 2000.   nan]
[40. 40. 50. ... 40. 40. 40.]
