# List vs Array

In [5]:
import numpy as np

In [6]:
list_a = [[1,2,3],[4,5,6]]

In [7]:
len(list_a)

2

In [8]:
array_a = np.array(list_a)

In [9]:
type(list_a)

list

In [10]:
type(array_a)

numpy.ndarray

In [11]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [12]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [13]:
array_a.shape

(2, 3)

In [15]:
print(len(list_a))
print(len(list_a[0]))

2
3


In [16]:
array_a.size

6

In [17]:
list_b = list_a[0] + list_a[1]
print(list_b)

[1, 2, 3, 4, 5, 6]


In [19]:
array_b = array_a[0] + array_a[1]
print(array_b)

[5 7 9]


In [20]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])