In [1]:
import numpy as np

In [2]:
array_a = np.array([1,2,3])
print(array_a)
print(array_a.shape)
print(array_a.ndim)

[1 2 3]
(3,)
1


In [3]:
array_b = np.array([[1],[2]])
print(array_b)
print(array_b.shape)
print(array_b.ndim)

[[1]
 [2]]
(2, 1)
2


In [4]:
matrix_c = np.array([[1,2,3],[4,5,6]])
print(matrix_c)
print(matrix_c.shape)
print(matrix_c.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


## Broadcasting universal function

In [5]:
np.add(array_a, matrix_c) # array_a is vector and 2nd one is matrix

array([[2, 4, 6],
       [5, 7, 9]])

In [6]:
np.add(array_b, matrix_c) # array_b is column vector and 2nd one is matrix

array([[2, 3, 4],
       [6, 7, 8]])

In [7]:
np.add(array_a, array_b)

array([[2, 3, 4],
       [3, 4, 5]])