# Data Types

In [1]:
import numpy as np

## Ndarrays

In [2]:
array_a = np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
type(array_a)

numpy.ndarray

## ndarray shape

In [16]:
print(array_a.shape)
print(array_a.ndim)

(3,)
1


## 2D array 

In [6]:
array_b = np.array([[1,2,3], [4,5,6]])

In [9]:
print(array_b)

[[1 2 3]
 [4 5 6]]


In [8]:
array_b.shape

(2, 3)

In [13]:
print(array_b.shape[0])  # 1st dimension i.e row
print(array_b.shape[1])  # 2nd dimension i.e column

2
3


## Scaler

In [17]:
array_c = np.array(13)

In [18]:
type(array_c)

numpy.ndarray

In [19]:
array_c.shape

()

In [20]:
array_c.ndim

0

In [21]:
array_c

array(13)

In [22]:
array_d = np.array([13])

In [23]:
print(array_d)

[13]


In [24]:
type(array_d)

numpy.ndarray

In [25]:
array_d.ndim

1

In [26]:
array_d.shape

(1,)