# Data Types

In [1]:
import numpy as np

## Ndarrays

In [2]:
array_a = np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
type(array_a)

numpy.ndarray

## ndarray shape

In [5]:
print(array_a.shape)
print(array_a.ndim)

(3,)
1


## 2D array 

In [6]:
array_b = np.array([[1,2,3], [4,5,6]])

In [7]:
print(array_b)

[[1 2 3]
 [4 5 6]]


In [8]:
array_b.shape

(2, 3)

In [9]:
print(array_b.shape[0])  # 1st dimension i.e row
print(array_b.shape[1])  # 2nd dimension i.e column

2
3


## Scaler

In [10]:
array_c = np.array(13)

In [11]:
type(array_c)

numpy.ndarray

In [12]:
array_c.shape

()

In [13]:
array_c.ndim

0

In [14]:
array_c

array(13)

In [15]:
array_d = np.array([13])

In [16]:
print(array_d)

[13]


In [17]:
type(array_d)

numpy.ndarray

In [18]:
array_d.ndim

1

In [19]:
array_d.shape

(1,)

## Types of data supported by NumPy

In [20]:
array_a = np.array([[1,2,3],[4,5,6]]) # with dtype = none
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
array_a = np.array([[1,2,3],[4,5,6]]) # with dtype=none
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
array_a = np.array([[1,2,3], [4,5,6]], dtype='float32') # with dtype=float32
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [30]:
array_a = np.array([[1,2,3], [4,5,6]], dtype=np.float16) # second way to pass dtype argument np.
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [32]:
array_a = np.array([[1,2,3], [4,5,6]], dtype=np.complex64) # second way to pass dtype argument np.complex64
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [33]:
array_a = np.array([[1,2,3], [4,5,6]], dtype=np.bool) # dtype=np.bool
array_a

array([[ True,  True,  True],
       [ True,  True,  True]])

In [34]:
array_a = np.array([[1,2,0], [4,5,6]], dtype=np.bool) # dtype=np.bool
array_a

array([[ True,  True, False],
       [ True,  True,  True]])

In [37]:
array_a = np.array([[10,2,3], [4,5,6]], dtype='str') # dtype=np.str is deprecated hence dtype=str
array_a

array([['10', '2', '3'],
       ['4', '5', '6']], dtype='<U2')