# NumPy Fundamentals

In [1]:
import numpy as np

## Indexing

In [2]:
array_a = np.array([[1,2,3], [4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

## Specific Values

In [5]:
array_a[1] # array_a is 2-D

array([4, 5, 6])

In [7]:
array_a[0][1] # 2nd element of 1st row

np.int64(2)

In [9]:
array_a[1][0] # 1st element of 2nd row

np.int64(4)

In [11]:
array_a[1,0] # similar to 1st element of 2nd row

np.int64(4)

In [12]:
array_a[:,0] # 1st column of array

array([1, 4])

## Negative Indices

In [14]:
array_b = np.array([1,2,3])
array_b[-1] # print the last element in 1-D array

np.int64(3)

In [15]:
array_a[-1] # this is 2-D array, hence will print the whole last row

array([4, 5, 6])

In [17]:
array_a[:,-1] # last column of 2-D array

array([3, 6])

## Assigning values

In [18]:
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [19]:
array_a[0] = 8 # all 1st row element change to value '8'
array_a

array([[8, 8, 8],
       [4, 5, 6]])

In [20]:
array_a[:,1] = 9 # all 2nd column element change to value '9'
array_a

array([[8, 9, 8],
       [4, 9, 6]])

In [21]:
list_a = [8,7,8]
array_a[0] = list_a
array_a

array([[8, 7, 8],
       [4, 9, 6]])

In [22]:
type(array_a[0])

numpy.ndarray

In [23]:
list_b = [1]
array_a[0] = list_b
array_a

array([[1, 1, 1],
       [4, 9, 6]])

In [25]:
# Go through all the rows and assign each one to each same value i.e '5' 
array_a[:] = 5  
array_a

array([[5, 5, 5],
       [5, 5, 5]])

## Element wise properties

In [44]:
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [27]:
array_b = np.array([[1,2,3], [4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
# add 2 in each element in 1-D array
array_a + 2

array([ 9, 10, 11])

In [29]:
array_b + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [32]:
# subtract 2 in each element in 1-D array
array_a - 2

array([5, 6, 7])

In [34]:
# subtract 2 in each element in 2-D array
array_b - 2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [36]:
# multiply each elemant in 1-D array
array_a * 2

array([14, 16, 18])

In [37]:
array_b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [42]:
# all operation only alter the value, not change the shape or size
array_a + array_b[0]

array([2, 4, 6])

In [45]:
array_a + array_b[1]

array([11, 13, 15])

In [46]:
array_a.size

3

In [48]:
# size of the element (row) in 2-D arrays 
array_b[0].size

3

In [50]:
array_a + array_b

array([[ 8, 10, 12],
       [11, 13, 15]])

In [51]:
array_a * array_b

array([[ 7, 16, 27],
       [28, 40, 54]])