In [2]:
import numpy as np
file_path = "/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/"

### Checking for Missing Values

In [4]:
# this is complete dataset hence no error
lending_co_data_numeric = np.loadtxt(file_path + "/raw/Lending-company-Numeric.csv", delimiter=",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [5]:
# To check for NaN or missing values
np.isnan(lending_co_data_numeric)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], shape=(1043, 6))

In [6]:
# Add all elements to check if any missing values
np.isnan(lending_co_data_numeric).sum()

np.int64(0)

In [10]:
# loading data having NaN values
lending_co_data_numeric_nan = np.genfromtxt(file_path + "/raw/Lending-company-Numeric-NAN.csv", delimiter=";")
lending_co_data_numeric_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [11]:
# To get the number of missing element
np.isnan(lending_co_data_numeric_nan).sum()

np.int64(260)

In [19]:
# filler value should greater than highest value
temporary_fill = np.nanmax(lending_co_data_numeric_nan).round() + 1
temporary_fill

np.float64(64002.0)

In [13]:
# fill the missing value with temporary fill
lending_co_data_numeric_nan = np.genfromtxt(file_path + "/raw/Lending-company-Numeric-NAN.csv", 
                                            delimiter=";",
                                           filling_values=temporary_fill)
lending_co_data_numeric_nan

array([[2.0000e+03, 4.0000e+01, 3.6500e+02, 3.1210e+03, 4.2410e+03,
        1.3621e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 3.0610e+03, 4.1710e+03,
        1.5041e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.1600e+03, 3.2800e+03,
        1.5340e+04],
       ...,
       [6.4002e+04, 4.0000e+01, 3.6500e+02, 4.2010e+03, 5.0010e+03,
        1.6600e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.0800e+03, 3.3200e+03,
        1.5600e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 4.6010e+03, 4.6010e+03,
        1.6600e+04]], shape=(1043, 6))

In [14]:
# confirm for any NAN in processed dataset
np.isnan(lending_co_data_numeric_nan).sum()

np.int64(0)

### Substituting missing values

In [15]:
lending_co_data_numeric_nan = np.genfromtxt(file_path + "/raw/Lending-company-Numeric-NAN.csv", 
                                            delimiter=";")
lending_co_data_numeric_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [18]:
temporary_mean = np.nanmean(lending_co_data_numeric_nan, axis=0).round(2)
temporary_mean

array([ 2250.25,    46.11,   365.  ,  3895.99,  5160.75, 16571.44])

In [22]:
# gen array from text file, fill value greater than sum
lending_co_data_numeric_nan = np.genfromtxt(file_path + '/raw/Lending-company-Numeric-NAN.csv',
                                           delimiter=";",
                                           filling_values=temporary_fill)
lending_co_data_numeric_nan

array([[2.0000e+03, 4.0000e+01, 3.6500e+02, 3.1210e+03, 4.2410e+03,
        1.3621e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 3.0610e+03, 4.1710e+03,
        1.5041e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.1600e+03, 3.2800e+03,
        1.5340e+04],
       ...,
       [6.4002e+04, 4.0000e+01, 3.6500e+02, 4.2010e+03, 5.0010e+03,
        1.6600e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.0800e+03, 3.3200e+03,
        1.5600e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 4.6010e+03, 4.6010e+03,
        1.6600e+04]], shape=(1043, 6))

In [24]:
lending_co_data_numeric_nan[:,0] = np.where(lending_co_data_numeric_nan[:,0] == temporary_fill, 
                                            temporary_mean[0], 
                                           lending_co_data_numeric_nan[:,0])
lending_co_data_numeric_nan[:,0]

array([2000.  , 2000.  , 1000.  , ..., 2250.25, 1000.  , 2000.  ],
      shape=(1043,))

In [26]:
np.mean(lending_co_data_numeric_nan[:,0], axis=0).round()

np.float64(2250.0)

In [28]:
for i in range(lending_co_data_numeric_nan.shape[1]):
    lending_co_data_numeric_nan[:,i] = np.where(lending_co_data_numeric_nan[:,i] == temporary_fill, 
                                            temporary_mean[0], 
                                           lending_co_data_numeric_nan[:,i])
lending_co_data_numeric_nan.mean(0)

array([ 2250.24784276,   147.54266539,   458.99137105,  3798.16347076,
        5054.71188878, 16214.436721  ])

### Reshaping

In [29]:
lending_co_data_numeric = np.genfromtxt(file_path + "/raw/Lending-company-Numeric.csv", delimiter=",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [30]:
lending_co_data_numeric.shape

(1043, 6)

In [31]:
np.reshape(lending_co_data_numeric, (6,1043))

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]],
      shape=(6, 1043))

In [32]:
# short version of reshape with (6, 1043)
np.transpose(lending_co_data_numeric)

array([[ 2000.,  2000.,  1000., ...,  2000.,  1000.,  2000.],
       [   40.,    40.,    40., ...,    40.,    40.,    40.],
       [  365.,   365.,   365., ...,   365.,   365.,   365.],
       [ 3121.,  3061.,  2160., ...,  4201.,  2080.,  4601.],
       [ 4241.,  4171.,  3280., ...,  5001.,  3320.,  4601.],
       [13621., 15041., 15340., ..., 16600., 15600., 16600.]],
      shape=(6, 1043))

In [33]:
np.reshape(lending_co_data_numeric, (3, 2086))

array([[ 2000.,    40.,   365., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  4601.,  4601., 16600.]],
      shape=(3, 2086))

In [34]:
# changing to 2d to 3d
np.reshape(lending_co_data_numeric, (2,3,1043))

array([[[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
        [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
        [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.]],

       [[ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
        [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
        [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]]],
      shape=(2, 3, 1043))

### Removing Values

In [35]:
np.delete
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [36]:
np.delete(lending_co_data_numeric, 0)

array([   40.,   365.,  3121., ...,  4601.,  4601., 16600.], shape=(6257,))

In [37]:
lending_co_data_numeric.size

6258

In [38]:
np.delete(lending_co_data_numeric, 0, axis=0)

array([[ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1042, 6))

In [39]:
np.delete(lending_co_data_numeric, 0, axis=1)

array([[   40.,   365.,  3121.,  4241., 13621.],
       [   40.,   365.,  3061.,  4171., 15041.],
       [   40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  4201.,  5001., 16600.],
       [   40.,   365.,  2080.,  3320., 15600.],
       [   40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 5))

In [40]:
# delete 2nd row
np.delete(lending_co_data_numeric, 1, axis=0)

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1042, 6))

In [42]:
# delete 2nd column
np.delete(lending_co_data_numeric, 1, axis=1)

array([[ 2000.,   365.,  3121.,  4241., 13621.],
       [ 2000.,   365.,  3061.,  4171., 15041.],
       [ 1000.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,   365.,  4201.,  5001., 16600.],
       [ 1000.,   365.,  2080.,  3320., 15600.],
       [ 2000.,   365.,  4601.,  4601., 16600.]], shape=(1043, 5))

In [44]:
np.delete(lending_co_data_numeric, (1,3,1042), axis=0)

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [ 2000.,    40.,   365.,  4240.,  5440., 16600.],
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.]], shape=(1040, 6))

In [45]:
np.delete(lending_co_data_numeric, (1,3), axis=1)

array([[ 2000.,   365.,  4241., 13621.],
       [ 2000.,   365.,  4171., 15041.],
       [ 1000.,   365.,  3280., 15340.],
       ...,
       [ 2000.,   365.,  5001., 16600.],
       [ 1000.,   365.,  3320., 15600.],
       [ 2000.,   365.,  4601., 16600.]], shape=(1043, 4))

### Sorting Data

In [46]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [47]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [48]:
np.sort(lending_co_data_numeric, axis=0)

array([[ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.8700e+03, -2.8700e+03,
        -3.5000e+02],
       [ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.5500e+03, -2.1000e+03,
         1.5000e+02],
       [ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.4500e+03, -2.0000e+03,
         1.1000e+03],
       ...,
       [ 9.0000e+03,  1.2500e+02,  3.6500e+02,  1.6751e+04,  1.8751e+04,
         5.4625e+04],
       [ 9.0000e+03,  1.6500e+02,  3.6500e+02,  1.7650e+04,  2.0001e+04,
         5.4625e+04],
       [ 9.0000e+03,  1.6500e+02,  3.6500e+02,  1.9001e+04,  2.2001e+04,
         6.4001e+04]], shape=(1043, 6))

In [49]:
np.set_printoptions(suppress=True)

In [50]:
np.sort(lending_co_data_numeric, axis=0)

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    35.,   365., -2550., -2100.,   150.],
       [ 1000.,    35.,   365., -2450., -2000.,  1100.],
       ...,
       [ 9000.,   125.,   365., 16751., 18751., 54625.],
       [ 9000.,   165.,   365., 17650., 20001., 54625.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]], shape=(1043, 6))

In [51]:
np.sort(lending_co_data_numeric, axis=-1)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [52]:
np.sort(lending_co_data_numeric, axis=None)

array([-2870., -2870., -2550., ..., 54625., 54625., 64001.], shape=(6258,))

In [54]:
# sorted the array in descending use -ve and multiply with -1
-np.sort(-lending_co_data_numeric)

array([[13621.,  4241.,  3121.,  2000.,   365.,    40.],
       [15041.,  4171.,  3061.,  2000.,   365.,    40.],
       [15340.,  3280.,  2160.,  1000.,   365.,    40.],
       ...,
       [16600.,  5001.,  4201.,  2000.,   365.,    40.],
       [15600.,  3320.,  2080.,  1000.,   365.,    40.],
       [16600.,  4601.,  4601.,  2000.,   365.,    40.]], shape=(1043, 6))