In [66]:
import numpy as np
import os
file_path = "/Users/vishalsaxena/Documents/DS_Workspace/data_processing_with_numpy/data/"

### Checking for Missing Values

In [2]:
# this is complete dataset hence no error
lending_co_data_numeric = np.loadtxt(file_path + "/raw/Lending-company-Numeric.csv", delimiter=",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [3]:
# To check for NaN or missing values
np.isnan(lending_co_data_numeric)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]], shape=(1043, 6))

In [4]:
# Add all elements to check if any missing values
np.isnan(lending_co_data_numeric).sum()

np.int64(0)

In [69]:
# loading data having NaN values
lending_co_data_numeric_nan = np.genfromtxt(file_path + "/raw/Lending-company-Numeric-NAN.csv", delimiter=";")
lending_co_data_numeric_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [6]:
# To get the number of missing element
np.isnan(lending_co_data_numeric_nan).sum()

np.int64(260)

In [7]:
# filler value should greater than highest value
temporary_fill = np.nanmax(lending_co_data_numeric_nan).round() + 1
temporary_fill

np.float64(64002.0)

In [8]:
# fill the missing value with temporary fill
lending_co_data_numeric_nan = np.genfromtxt(file_path + "/raw/Lending-company-Numeric-NAN.csv", 
                                            delimiter=";",
                                           filling_values=temporary_fill)
lending_co_data_numeric_nan

array([[2.0000e+03, 4.0000e+01, 3.6500e+02, 3.1210e+03, 4.2410e+03,
        1.3621e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 3.0610e+03, 4.1710e+03,
        1.5041e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.1600e+03, 3.2800e+03,
        1.5340e+04],
       ...,
       [6.4002e+04, 4.0000e+01, 3.6500e+02, 4.2010e+03, 5.0010e+03,
        1.6600e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.0800e+03, 3.3200e+03,
        1.5600e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 4.6010e+03, 4.6010e+03,
        1.6600e+04]], shape=(1043, 6))

In [9]:
# confirm for any NAN in processed dataset
np.isnan(lending_co_data_numeric_nan).sum()

np.int64(0)

### Substituting missing values

In [10]:
lending_co_data_numeric_nan = np.genfromtxt(file_path + "/raw/Lending-company-Numeric-NAN.csv", 
                                            delimiter=";")
lending_co_data_numeric_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [11]:
temporary_mean = np.nanmean(lending_co_data_numeric_nan, axis=0).round(2)
temporary_mean

array([ 2250.25,    46.11,   365.  ,  3895.99,  5160.75, 16571.44])

In [12]:
# gen array from text file, fill value greater than sum
lending_co_data_numeric_nan = np.genfromtxt(file_path + '/raw/Lending-company-Numeric-NAN.csv',
                                           delimiter=";",
                                           filling_values=temporary_fill)
lending_co_data_numeric_nan

array([[2.0000e+03, 4.0000e+01, 3.6500e+02, 3.1210e+03, 4.2410e+03,
        1.3621e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 3.0610e+03, 4.1710e+03,
        1.5041e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.1600e+03, 3.2800e+03,
        1.5340e+04],
       ...,
       [6.4002e+04, 4.0000e+01, 3.6500e+02, 4.2010e+03, 5.0010e+03,
        1.6600e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.0800e+03, 3.3200e+03,
        1.5600e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 4.6010e+03, 4.6010e+03,
        1.6600e+04]], shape=(1043, 6))

In [13]:
lending_co_data_numeric_nan[:,0] = np.where(lending_co_data_numeric_nan[:,0] == temporary_fill, 
                                            temporary_mean[0], 
                                           lending_co_data_numeric_nan[:,0])
lending_co_data_numeric_nan[:,0]

array([2000.  , 2000.  , 1000.  , ..., 2250.25, 1000.  , 2000.  ],
      shape=(1043,))

In [14]:
np.mean(lending_co_data_numeric_nan[:,0], axis=0).round()

np.float64(2250.0)

In [15]:
for i in range(lending_co_data_numeric_nan.shape[1]):
    lending_co_data_numeric_nan[:,i] = np.where(lending_co_data_numeric_nan[:,i] == temporary_fill, 
                                            temporary_mean[0], 
                                           lending_co_data_numeric_nan[:,i])
lending_co_data_numeric_nan.mean(0)

array([ 2250.24784276,   147.54266539,   458.99137105,  3798.16347076,
        5054.71188878, 16214.436721  ])

### Reshaping

In [16]:
lending_co_data_numeric = np.genfromtxt(file_path + "/raw/Lending-company-Numeric.csv", delimiter=",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [17]:
lending_co_data_numeric.shape

(1043, 6)

In [18]:
np.reshape(lending_co_data_numeric, (6,1043))

array([[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
       [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.],
       [ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
       [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]],
      shape=(6, 1043))

In [19]:
# short version of reshape with (6, 1043)
np.transpose(lending_co_data_numeric)

array([[ 2000.,  2000.,  1000., ...,  2000.,  1000.,  2000.],
       [   40.,    40.,    40., ...,    40.,    40.,    40.],
       [  365.,   365.,   365., ...,   365.,   365.,   365.],
       [ 3121.,  3061.,  2160., ...,  4201.,  2080.,  4601.],
       [ 4241.,  4171.,  3280., ...,  5001.,  3320.,  4601.],
       [13621., 15041., 15340., ..., 16600., 15600., 16600.]],
      shape=(6, 1043))

In [20]:
np.reshape(lending_co_data_numeric, (3, 2086))

array([[ 2000.,    40.,   365., ...,    50.,   365.,  5350.],
       [ 6850., 15150.,  1000., ..., 16600.,  2000.,    40.],
       [  365.,  3441.,  4661., ...,  4601.,  4601., 16600.]],
      shape=(3, 2086))

In [21]:
# changing to 2d to 3d
np.reshape(lending_co_data_numeric, (2,3,1043))

array([[[ 2000.,    40.,   365., ...,   365.,  1581.,  3041.],
        [12277.,  2000.,    40., ...,    50.,   365.,  5350.],
        [ 6850., 15150.,  1000., ...,  2000.,    40.,   365.]],

       [[ 3101.,  4351., 16600., ..., 16600.,  2000.,    40.],
        [  365.,  3441.,  4661., ...,  8450., 22250.,  2000.],
        [   40.,   365.,  3701., ...,  4601.,  4601., 16600.]]],
      shape=(2, 3, 1043))

### Removing Values

In [22]:
np.delete
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [23]:
np.delete(lending_co_data_numeric, 0)

array([   40.,   365.,  3121., ...,  4601.,  4601., 16600.], shape=(6257,))

In [24]:
lending_co_data_numeric.size

6258

In [25]:
np.delete(lending_co_data_numeric, 0, axis=0)

array([[ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1042, 6))

In [26]:
np.delete(lending_co_data_numeric, 0, axis=1)

array([[   40.,   365.,  3121.,  4241., 13621.],
       [   40.,   365.,  3061.,  4171., 15041.],
       [   40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  4201.,  5001., 16600.],
       [   40.,   365.,  2080.,  3320., 15600.],
       [   40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 5))

In [27]:
# delete 2nd row
np.delete(lending_co_data_numeric, 1, axis=0)

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1042, 6))

In [28]:
# delete 2nd column
np.delete(lending_co_data_numeric, 1, axis=1)

array([[ 2000.,   365.,  3121.,  4241., 13621.],
       [ 2000.,   365.,  3061.,  4171., 15041.],
       [ 1000.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,   365.,  4201.,  5001., 16600.],
       [ 1000.,   365.,  2080.,  3320., 15600.],
       [ 2000.,   365.,  4601.,  4601., 16600.]], shape=(1043, 5))

In [29]:
np.delete(lending_co_data_numeric, (1,3,1042), axis=0)

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [ 2000.,    40.,   365.,  4240.,  5440., 16600.],
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.]], shape=(1040, 6))

In [30]:
np.delete(lending_co_data_numeric, (1,3), axis=1)

array([[ 2000.,   365.,  4241., 13621.],
       [ 2000.,   365.,  4171., 15041.],
       [ 1000.,   365.,  3280., 15340.],
       ...,
       [ 2000.,   365.,  5001., 16600.],
       [ 1000.,   365.,  3320., 15600.],
       [ 2000.,   365.,  4601., 16600.]], shape=(1043, 4))

### Sorting Data

In [31]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [32]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [33]:
np.sort(lending_co_data_numeric, axis=0)

array([[ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.8700e+03, -2.8700e+03,
        -3.5000e+02],
       [ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.5500e+03, -2.1000e+03,
         1.5000e+02],
       [ 1.0000e+03,  3.5000e+01,  3.6500e+02, -2.4500e+03, -2.0000e+03,
         1.1000e+03],
       ...,
       [ 9.0000e+03,  1.2500e+02,  3.6500e+02,  1.6751e+04,  1.8751e+04,
         5.4625e+04],
       [ 9.0000e+03,  1.6500e+02,  3.6500e+02,  1.7650e+04,  2.0001e+04,
         5.4625e+04],
       [ 9.0000e+03,  1.6500e+02,  3.6500e+02,  1.9001e+04,  2.2001e+04,
         6.4001e+04]], shape=(1043, 6))

In [34]:
np.set_printoptions(suppress=True)

In [35]:
np.sort(lending_co_data_numeric, axis=0)

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    35.,   365., -2550., -2100.,   150.],
       [ 1000.,    35.,   365., -2450., -2000.,  1100.],
       ...,
       [ 9000.,   125.,   365., 16751., 18751., 54625.],
       [ 9000.,   165.,   365., 17650., 20001., 54625.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]], shape=(1043, 6))

In [36]:
np.sort(lending_co_data_numeric, axis=-1)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [37]:
np.sort(lending_co_data_numeric, axis=None)

array([-2870., -2870., -2550., ..., 54625., 54625., 64001.], shape=(6258,))

In [38]:
# sorted the array in descending use -ve and multiply with -1
-np.sort(-lending_co_data_numeric)

array([[13621.,  4241.,  3121.,  2000.,   365.,    40.],
       [15041.,  4171.,  3061.,  2000.,   365.,    40.],
       [15340.,  3280.,  2160.,  1000.,   365.,    40.],
       ...,
       [16600.,  5001.,  4201.,  2000.,   365.,    40.],
       [15600.,  3320.,  2080.,  1000.,   365.,    40.],
       [16600.,  4601.,  4601.,  2000.,   365.,    40.]], shape=(1043, 6))

## Argument functions
### np.argsort()

In [39]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [40]:
np.argsort(lending_co_data_numeric)

array([[1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       ...,
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5],
       [1, 2, 0, 3, 4, 5]], shape=(1043, 6))

In [41]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [42]:
np.argsort(lending_co_data_numeric, axis=0)

array([[ 537,  443,    0,   32,   32,  482],
       [ 639,  327,  687,  166,  166,  493],
       [ 849,  432,  688,   85,   85,  166],
       ...,
       [  27,  326,  355,  568, 1019,  568],
       [ 277,   27,  357,  718, 1033,  534],
       [ 420,  408, 1042,  912,  912,   27]], shape=(1043, 6))

In [43]:
lending_co_data_numeric[0,2]

np.float64(365.0)

In [44]:
np.max(lending_co_data_numeric[:,2])

np.float64(365.0)

In [45]:
lending_co_data_numeric[482, 5]

np.float64(-350.0)

In [46]:
np.min(lending_co_data_numeric[:,5])

np.float64(-350.0)

In [47]:
np.sort(lending_co_data_numeric, axis=0)

array([[ 1000.,    35.,   365., -2870., -2870.,  -350.],
       [ 1000.,    35.,   365., -2550., -2100.,   150.],
       [ 1000.,    35.,   365., -2450., -2000.,  1100.],
       ...,
       [ 9000.,   125.,   365., 16751., 18751., 54625.],
       [ 9000.,   165.,   365., 17650., 20001., 54625.],
       [ 9000.,   165.,   365., 19001., 22001., 64001.]], shape=(1043, 6))

In [48]:
np.argsort(lending_co_data_numeric[:,0])

array([537, 639, 849, ...,  27, 277, 420], shape=(1043,))

In [49]:
condition_sorted_data = lending_co_data_numeric[np.argsort(lending_co_data_numeric[:,0])]
condition_sorted_data

array([[ 1000.,    40.,   365.,  2200.,  3400., 15600.],
       [ 1000.,    40.,   365.,  2200.,  3800., 15600.],
       [ 1000.,    40.,   365.,  2000.,  3950., 15600.],
       ...,
       [ 9000.,   165.,   365., 14501., 16846., 64001.],
       [ 9000.,   125.,   365., 12001., 15751., 38626.],
       [ 9000.,   125.,   365., 12251., 14251., 25626.]], shape=(1043, 6))

In [50]:
np.sort(lending_co_data_numeric[:,3])

array([-2870., -2550., -2450., ..., 16751., 17650., 19001.], shape=(1043,))

In [51]:
# condition_sorted_data = lending_co_data_numeric[np.sort(lending_co_data_numeric[:,3])]

In [52]:
lending_co_data_numeric.argsort(axis=0)

array([[ 537,  443,    0,   32,   32,  482],
       [ 639,  327,  687,  166,  166,  493],
       [ 849,  432,  688,   85,   85,  166],
       ...,
       [  27,  326,  355,  568, 1019,  568],
       [ 277,   27,  357,  718, 1033,  534],
       [ 420,  408, 1042,  912,  912,   27]], shape=(1043, 6))

In [53]:
lending_co_data_numeric # does

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [54]:
np.sort(lending_co_data_numeric)

array([[   40.,   365.,  2000.,  3121.,  4241., 13621.],
       [   40.,   365.,  2000.,  3061.,  4171., 15041.],
       [   40.,   365.,  1000.,  2160.,  3280., 15340.],
       ...,
       [   40.,   365.,  2000.,  4201.,  5001., 16600.],
       [   40.,   365.,  1000.,  2080.,  3320., 15600.],
       [   40.,   365.,  2000.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [55]:
# print(lending_co_data_numeric.sort())

### np.argwhere()

In [56]:
np.argwhere(lending_co_data_numeric)

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [1042,    3],
       [1042,    4],
       [1042,    5]], shape=(6256, 2))

In [57]:
np.argwhere(lending_co_data_numeric == False)

array([[116,   4],
       [430,   3]])

In [58]:
lending_co_data_numeric[116]

array([ 1000.,    50.,   365., -1450.,     0., 13850.])

In [59]:
lending_co_data_numeric[430]

array([1000.,   50.,  365.,    0.,  550., 5650.])

In [62]:
np.argwhere(lending_co_data_numeric < 1000)

array([[   0,    1],
       [   0,    2],
       [   1,    1],
       ...,
       [1041,    2],
       [1042,    1],
       [1042,    2]], shape=(2200, 2))

In [61]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [63]:
np.argwhere((lending_co_data_numeric < 1000) & (lending_co_data_numeric % 2 == 0))

array([[   0,    1],
       [   1,    1],
       [   2,    1],
       ...,
       [1040,    1],
       [1041,    1],
       [1042,    1]], shape=(1132, 2))

In [77]:
lending_co_data_numeric_nan_again = np.genfromtxt(os.path.join(file_path, 'raw/Lending-company-Numeric-NAN.csv'),
                                                 delimiter=";")
lending_co_data_numeric_nan_again

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [78]:
np.isnan(lending_co_data_numeric_nan_again).sum()

np.int64(260)

In [80]:
np.argwhere(np.isnan(lending_co_data_numeric_nan_again))

array([[  11,    3],
       [  15,    3],
       [  27,    3],
       [  58,    3],
       [  60,    4],
       [  85,    4],
       [ 117,    5],
       [ 152,    1],
       [ 152,    2],
       [ 152,    4],
       [ 172,    1],
       [ 175,    1],
       [ 175,    2],
       [ 176,    3],
       [ 177,    4],
       [ 178,    5],
       [ 211,    3],
       [ 229,    0],
       [ 230,    1],
       [ 237,    1],
       [ 247,    3],
       [ 251,    5],
       [ 252,    4],
       [ 258,    1],
       [ 260,    3],
       [ 262,    4],
       [ 271,    5],
       [ 272,    4],
       [ 284,    2],
       [ 284,    3],
       [ 297,    1],
       [ 297,    2],
       [ 300,    3],
       [ 315,    3],
       [ 315,    5],
       [ 327,    4],
       [ 336,    4],
       [ 343,    0],
       [ 344,    2],
       [ 346,    2],
       [ 363,    3],
       [ 375,    3],
       [ 377,    2],
       [ 398,    5],
       [ 416,    4],
       [ 428,    0],
       [ 432,    1],
       [ 433,

In [81]:
lending_co_data_numeric_nan_again[11,3]

np.float64(nan)

In [82]:
lending_co_data_numeric_nan_again[175]

array([ 2000.,    nan,    nan,  1851.,  3051., 13561.])

In [84]:
for array_index in np.argwhere(np.isnan(lending_co_data_numeric_nan_again)):
    print(f"row={array_index[0]}, column={array_index[1]}")

row=11, column=3
row=15, column=3
row=27, column=3
row=58, column=3
row=60, column=4
row=85, column=4
row=117, column=5
row=152, column=1
row=152, column=2
row=152, column=4
row=172, column=1
row=175, column=1
row=175, column=2
row=176, column=3
row=177, column=4
row=178, column=5
row=211, column=3
row=229, column=0
row=230, column=1
row=237, column=1
row=247, column=3
row=251, column=5
row=252, column=4
row=258, column=1
row=260, column=3
row=262, column=4
row=271, column=5
row=272, column=4
row=284, column=2
row=284, column=3
row=297, column=1
row=297, column=2
row=300, column=3
row=315, column=3
row=315, column=5
row=327, column=4
row=336, column=4
row=343, column=0
row=344, column=2
row=346, column=2
row=363, column=3
row=375, column=3
row=377, column=2
row=398, column=5
row=416, column=4
row=428, column=0
row=432, column=1
row=433, column=3
row=434, column=2
row=440, column=3
row=441, column=1
row=446, column=2
row=455, column=1
row=456, column=2
row=458, column=2
row=461, column=

In [85]:
for array_index in np.argwhere(np.isnan(lending_co_data_numeric_nan_again)):
    lending_co_data_numeric_nan_again[array_index[0], array_index[1]] = 0

In [86]:
lending_co_data_numeric_nan_again[175]

array([ 2000.,     0.,     0.,  1851.,  3051., 13561.])

In [87]:
np.isnan(lending_co_data_numeric_nan_again).sum()

np.int64(0)

### Shuffle data

In [90]:
sliced_lending_co_data_numeric = np.loadtxt(os.path.join(file_path, 'raw/Lending-company-Numeric.csv'),
                                           delimiter=",")[:8]
sliced_lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [91]:
np.random.shuffle(sliced_lending_co_data_numeric)

In [92]:
sliced_lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.]])

In [93]:
np.random.shuffle(sliced_lending_co_data_numeric)
sliced_lending_co_data_numeric

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.]])

In [94]:
lending_co_data_numeric = np.loadtxt(os.path.join(file_path, 'raw/Lending-company-Numeric.csv'),
                                           delimiter=",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [95]:
np.random.shuffle(lending_co_data_numeric)
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3701.,  4301., 10201.],
       [ 2000.,    50.,   365.,  3301.,  4951., 20250.],
       [ 2000.,    40.,   365.,  3480.,  4160., 14760.],
       ...,
       [ 1000.,    50.,   365.,   550.,  1150., 10770.],
       [ 2000.,    40.,   365.,  3401.,  4601., 16600.],
       [ 1000.,    50.,   365., -1860.,  -440., 12200.]], shape=(1043, 6))

### Casting

In [96]:
lending_co_data_numeric.astype(dtype = np.int32)

array([[ 2000,    40,   365,  3701,  4301, 10201],
       [ 2000,    50,   365,  3301,  4951, 20250],
       [ 2000,    40,   365,  3480,  4160, 14760],
       ...,
       [ 1000,    50,   365,   550,  1150, 10770],
       [ 2000,    40,   365,  3401,  4601, 16600],
       [ 1000,    50,   365, -1860,  -440, 12200]],
      shape=(1043, 6), dtype=int32)

In [97]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3701.,  4301., 10201.],
       [ 2000.,    50.,   365.,  3301.,  4951., 20250.],
       [ 2000.,    40.,   365.,  3480.,  4160., 14760.],
       ...,
       [ 1000.,    50.,   365.,   550.,  1150., 10770.],
       [ 2000.,    40.,   365.,  3401.,  4601., 16600.],
       [ 1000.,    50.,   365., -1860.,  -440., 12200.]], shape=(1043, 6))

In [99]:
lending_co_data_string = lending_co_data_numeric.astype(dtype=np.str_)
lending_co_data_string

array([['2000.0', '40.0', '365.0', '3701.0', '4301.0', '10201.0'],
       ['2000.0', '50.0', '365.0', '3301.0', '4951.0', '20250.0'],
       ['2000.0', '40.0', '365.0', '3480.0', '4160.0', '14760.0'],
       ...,
       ['1000.0', '50.0', '365.0', '550.0', '1150.0', '10770.0'],
       ['2000.0', '40.0', '365.0', '3401.0', '4601.0', '16600.0'],
       ['1000.0', '50.0', '365.0', '-1860.0', '-440.0', '12200.0']],
      shape=(1043, 6), dtype='<U32')

In [102]:
# lending_co_data_string.astype(dtype=np.int32) raise ValueError
lending_co_data_float = lending_co_data_string.astype(dtype=np.float32)
lending_co_data_float

array([[ 2000.,    40.,   365.,  3701.,  4301., 10201.],
       [ 2000.,    50.,   365.,  3301.,  4951., 20250.],
       [ 2000.,    40.,   365.,  3480.,  4160., 14760.],
       ...,
       [ 1000.,    50.,   365.,   550.,  1150., 10770.],
       [ 2000.,    40.,   365.,  3401.,  4601., 16600.],
       [ 1000.,    50.,   365., -1860.,  -440., 12200.]],
      shape=(1043, 6), dtype=float32)

### Stripping values

In [103]:
lending_co_total_price = np.genfromtxt(os.path.join(file_path, 'raw/Lending-Company-Total-Price.csv'),
                                      delimiter=",",
                                      dtype=np.str_,
                                      skip_header=1,
                                      usecols=[1,2,4])
lending_co_total_price

array([['id_1', 'Product B', 'Location 2'],
       ['id_2', 'Product B', 'Location 3'],
       ['id_3', 'Product C', 'Location 5'],
       ...,
       ['id_413', 'Product B', 'Location 135'],
       ['id_414', 'Product C', 'Location 200'],
       ['id_415', 'Product A', 'Location 8']],
      shape=(415, 3), dtype='<U12')

In [104]:
print(np.__version__)

2.2.4


In [105]:
np.chararray.strip(lending_co_total_price[:,0], "id_")

/var/folders/jx/cc9brgl143z9wt4bc65wylz40000gn/T/ipykernel_9301/1339721210.py:1: DeprecationWarning: `np.chararray` is deprecated and will be removed from the main namespace in the future. Use an array with a string or bytes dtype instead.
  np.chararray.strip(lending_co_total_price[:,0], "id_")


array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34',
       '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45',
       '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56',
       '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67',
       '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78',
       '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89',
       '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100',
       '101', '102', '103', '104', '105', '106', '107', '108', '109',
       '110', '111', '112', '113', '114', '115', '116', '117', '118',
       '119', '120', '121', '122', '123', '124', '125', '126', '127',
       '128', '129', '130', '131', '132', '133', '134', '135', '136',
       '137', '138', '139', '140', '141', '142', '143', '144', '1

In [106]:
np.char.strip(lending_co_total_price[:,0], 'id_')

array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34',
       '35', '36', '37', '38', '39', '40', '41', '42', '43', '44', '45',
       '46', '47', '48', '49', '50', '51', '52', '53', '54', '55', '56',
       '57', '58', '59', '60', '61', '62', '63', '64', '65', '66', '67',
       '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78',
       '79', '80', '81', '82', '83', '84', '85', '86', '87', '88', '89',
       '90', '91', '92', '93', '94', '95', '96', '97', '98', '99', '100',
       '101', '102', '103', '104', '105', '106', '107', '108', '109',
       '110', '111', '112', '113', '114', '115', '116', '117', '118',
       '119', '120', '121', '122', '123', '124', '125', '126', '127',
       '128', '129', '130', '131', '132', '133', '134', '135', '136',
       '137', '138', '139', '140', '141', '142', '143', '144', '1

In [115]:
lending_co_total_price[:,0] = np.char.strip(lending_co_total_price[:,0], 'id_')
lending_co_total_price[:,1] = np.char.strip(lending_co_total_price[:,1], 'Product ')
lending_co_total_price[:,2] = np.char.strip(lending_co_total_price[:,2], 'Location ')
lending_co_total_price

array([['1', 'B', '2'],
       ['2', 'B', '3'],
       ['3', 'C', '5'],
       ...,
       ['413', 'B', '135'],
       ['414', 'C', '200'],
       ['415', '1', '8']], shape=(415, 3), dtype='<U12')

In [117]:
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'A', '1', lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'B', '2', lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'C', '3', lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'D', '4', lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'E', '5', lending_co_total_price[:,1])
lending_co_total_price[:,1] = np.where(lending_co_total_price[:,1] == 'F', '6', lending_co_total_price[:,1])
lending_co_total_price

array([['1', '2', '2'],
       ['2', '2', '3'],
       ['3', '3', '5'],
       ...,
       ['413', '2', '135'],
       ['414', '3', '200'],
       ['415', '1', '8']], shape=(415, 3), dtype='<U12')

In [119]:
lending_co_total_price = lending_co_total_price.astype(dtype=np.int32)
lending_co_total_price

array([[  1,   2,   2],
       [  2,   2,   3],
       [  3,   3,   5],
       ...,
       [413,   2, 135],
       [414,   3, 200],
       [415,   1,   8]], shape=(415, 3), dtype=int32)

### Stacking arrays (np.stack, np.vstack, np.hstack, np.dstack)

In [125]:
# '''
# 1. Reading numeric data set
# 2. Reading NaN data set
# 3. Find the temporay fill
# 4. Find the temporary mean
# 5. Reading NaN data set with temporary fill
# 6. Execute loop to fill the temporary mean to replace temporary fill
# '''
lending_co_data_numeric = np.genfromtxt(os.path.join(file_path, 'raw/Lending-company-Numeric.csv'), delimiter=",")
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [128]:
lending_co_data_numeric_nan = np.genfromtxt(os.path.join(file_path, 'raw/Lending-company-Numeric-NAN.csv'), 
                                            delimiter=";")
lending_co_data_numeric_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [130]:
temporary_fill = np.nanmax(lending_co_data_numeric_nan).round(2) + 1
temporary_fill

np.float64(64002.0)

In [131]:
temporary_mean = np.nanmean(lending_co_data_numeric_nan, axis=0).round(2)
temporary_mean

array([ 2250.25,    46.11,   365.  ,  3895.99,  5160.75, 16571.44])

In [132]:
lending_co_data_numeric_nan = np.genfromtxt(os.path.join(file_path, 'raw/Lending-company-Numeric-NAN.csv'), 
                                            delimiter=";",
                                           filling_values=temporary_fill)
lending_co_data_numeric_nan

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [64002.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [133]:
for i in range(lending_co_data_numeric_nan.shape[1]):
    lending_co_data_numeric_nan[:,i] = np.where(lending_co_data_numeric_nan[:,i] == temporary_fill, 
                                                temporary_mean[i],
                                               lending_co_data_numeric_nan[:,i])
lending_co_data_numeric_nan

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]],
      shape=(1043, 6))

In [136]:
# stacking them on top of one another
np.stack((lending_co_data_numeric[:,0], lending_co_data_numeric[:,1])) 

array([[2000., 2000., 1000., ..., 2000., 1000., 2000.],
       [  40.,   40.,   40., ...,   40.,   40.,   40.]], shape=(2, 1043))

In [137]:
# stacking them on top of one another with chenage sequence
np.stack((lending_co_data_numeric[:,1], lending_co_data_numeric[:,0])) 

array([[  40.,   40.,   40., ...,   40.,   40.,   40.],
       [2000., 2000., 1000., ..., 2000., 1000., 2000.]], shape=(2, 1043))

In [148]:
print(lending_co_data_numeric[:,1].shape)
print(lending_co_data_numeric[:,0].shape)

(1043,)
(1043,)


In [139]:
# stacking them side by side
np.stack((lending_co_data_numeric[:,0], lending_co_data_numeric[:,1]), axis=1) 

array([[2000.,   40.],
       [2000.,   40.],
       [1000.,   40.],
       ...,
       [2000.,   40.],
       [1000.,   40.],
       [2000.,   40.]], shape=(1043, 2))

In [141]:
# multiple elements
np.stack((lending_co_data_numeric[:,0], lending_co_data_numeric[:,1], lending_co_data_numeric[:,2]), axis=1)

array([[2000.,   40.,  365.],
       [2000.,   40.,  365.],
       [1000.,   40.,  365.],
       ...,
       [2000.,   40.,  365.],
       [1000.,   40.,  365.],
       [2000.,   40.,  365.]], shape=(1043, 3))

In [143]:
np.vstack((lending_co_data_numeric, lending_co_data_numeric_nan))

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]],
      shape=(2086, 6))

In [144]:
np.hstack([lending_co_data_numeric, lending_co_data_numeric_nan])

array([[ 2000.,    40.,   365., ...,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365., ...,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365., ...,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., ...,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365., ...,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365., ...,  4601.,  4601., 16600.]],
      shape=(1043, 12))

In [145]:
np.dstack([lending_co_data_numeric, lending_co_data_numeric_nan])

array([[[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3121.  ,  3121.  ],
        [ 4241.  ,  4241.  ],
        [13621.  , 13621.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 3061.  ,  3061.  ],
        [ 4171.  ,  4171.  ],
        [15041.  , 15041.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2160.  ,  2160.  ],
        [ 3280.  ,  3280.  ],
        [15340.  , 15340.  ]],

       ...,

       [[ 2000.  ,  2250.25],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 4201.  ,  4201.  ],
        [ 5001.  ,  5001.  ],
        [16600.  , 16600.  ]],

       [[ 1000.  ,  1000.  ],
        [   40.  ,    40.  ],
        [  365.  ,   365.  ],
        [ 2080.  ,  2080.  ],
        [ 3320.  ,  3320.  ],
        [15600.  , 15600.  ]],

       [[ 2000.  ,  2000.  ],
        [   40.  ,    40.  ],
        [  365.  

### Concatenating

In [149]:
np.concatenate([lending_co_data_numeric, lending_co_data_numeric_nan])

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]],
      shape=(2086, 6))

In [152]:
a = np.array([[1, 2]])
b = np.array([[3, 4]])
c = np.array([[5, 6]])

np.concatenate((a, b, c), axis=0).shape  # shape: (2, 2)
# Stacks rows

np.stack((a, b, c), axis=0).shape       # shape: (2, 1, 2)
# Adds a new outer dimension

(3, 1, 2)

In [153]:
np.concatenate((a, b, c), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [154]:
np.concatenate((a, b, c), axis=0).shape

(3, 2)

In [155]:
np.stack((a, b, c), axis=0)

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]]])

In [156]:
np.stack((a, b, c), axis=0).shape

(3, 1, 2)

In [158]:
np.concatenate([lending_co_data_numeric[0,:], lending_co_data_numeric[:,0]])

array([2000.,   40.,  365., ..., 2000., 1000., 2000.], shape=(1049,))

In [160]:
# np.concatenate([lending_co_data_numeric[:,:], lending_co_data_numeric[:,0]]) # different dimension raise error
np.concatenate([lending_co_data_numeric, lending_co_data_numeric[1:,:]])

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(2085, 6))

### Finding Unique in arrays

In [161]:
lending_co_data_numeric

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]], shape=(1043, 6))

In [162]:
np.unique(lending_co_data_numeric)

array([-2870., -2550., -2450., ..., 52751., 54625., 64001.], shape=(1140,))

In [164]:
np.unique(lending_co_data_numeric[:,1], return_counts=True)

(array([ 35.,  40.,  50., 125., 165.]), array([  4, 567, 451,  19,   2]))

In [165]:
np.unique(lending_co_data_numeric[:,1], return_counts=True, return_index=True)

(array([ 35.,  40.,  50., 125., 165.]),
 array([327,   0,   4,  19,  27]),
 array([  4, 567, 451,  19,   2]))