## Working with Arrays

In [1]:
import numpy as np

In [2]:
matrix_a = np.array([[1,2,3],[4,5,6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

## Basic Slicing

In [3]:
matrix_a[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
matrix_a[0:0]

array([], shape=(0, 3), dtype=int64)

In [7]:
matrix_a[0:1].shape

(1, 3)

In [8]:
matrix_a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# column wise slicing
type(matrix_a[:,0:1])

numpy.ndarray

In [11]:
matrix_a[:1] # 1st row

array([[1, 2, 3]])

In [12]:
matrix_a[1:] # 2nd row

array([[4, 5, 6]])

In [13]:
matrix_a[2:]

array([], shape=(0, 3), dtype=int64)

In [14]:
matrix_a[:-1]

array([[1, 2, 3]])

In [15]:
matrix_a[:,1:]

array([[2, 3],
       [5, 6]])

In [16]:
matrix_a[1:,1:]

array([[5, 6]])

## Stepwise Slicing

In [17]:
matrix_b = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_b

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [18]:
print(matrix_b.ndim)
print(matrix_b.shape)

2
(3, 5)


In [19]:
matrix_b[:]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [25]:
matrix_b[::2] # slicing every other row i.e 1st and 3rd rows

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [27]:
matrix_b[::2,::2]

array([[1, 1, 0],
       [4, 3, 0]])

## Conditional Slicing

In [28]:
matrix_c = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_c

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [31]:
matrix_c[:,0]

array([1, 3, 4])

In [32]:
# condition like each element is greater than 2
matrix_c[:,0] > 2

array([False,  True,  True])

In [34]:
matrix_c[:,:] > 2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [35]:
matrix_c[matrix_c[:,:] > 2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [36]:
matrix_c[matrix_c[:,:] >= 2]

array([2, 3, 6, 6, 7, 4, 4, 5, 3, 8])

In [37]:
matrix_c[matrix_c[:,:] % 2 == 0]

array([2, 0, 6, 6, 4, 4, 8, 0])

In [38]:
# multiple condition
matrix_c[(matrix_c[:,:] % 2 == 0) & (matrix_c[:,:] <= 4)]

array([2, 0, 4, 4, 0])