## Working with Arrays

In [1]:
import numpy as np

In [2]:
matrix_a = np.array([[1,2,3],[4,5,6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

## Basic Slicing

In [3]:
matrix_a[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
matrix_a[0:0]

array([], shape=(0, 3), dtype=int64)

In [38]:
matrix_a[0:1].shape

(1, 3)

In [6]:
matrix_a[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# column wise slicing
type(matrix_a[:,0:1])

numpy.ndarray

In [8]:
matrix_a[:1] # 1st row

array([[1, 2, 3]])

In [9]:
matrix_a[1:] # 2nd row

array([[4, 5, 6]])

In [10]:
matrix_a[2:]

array([], shape=(0, 3), dtype=int64)

In [11]:
matrix_a[:-1]

array([[1, 2, 3]])

In [12]:
matrix_a[:,1:]

array([[2, 3],
       [5, 6]])

In [13]:
matrix_a[1:,1:]

array([[5, 6]])

## Stepwise Slicing

In [14]:
matrix_b = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_b

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [15]:
print(matrix_b.ndim)
print(matrix_b.shape)

2
(3, 5)


In [16]:
matrix_b[:]

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [17]:
matrix_b[::2] # slicing every other row i.e 1st and 3rd rows

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [18]:
matrix_b[::2,::2]

array([[1, 1, 0],
       [4, 3, 0]])

## Conditional Slicing

In [19]:
matrix_c = np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_c

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [20]:
matrix_c[:,0]

array([1, 3, 4])

In [21]:
# condition like each element is greater than 2
matrix_c[:,0] > 2

array([False,  True,  True])

In [22]:
matrix_c[:,:] > 2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [23]:
matrix_c[matrix_c[:,:] > 2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [24]:
matrix_c[matrix_c[:,:] >= 2]

array([2, 3, 6, 6, 7, 4, 4, 5, 3, 8])

In [25]:
matrix_c[matrix_c[:,:] % 2 == 0]

array([2, 0, 6, 6, 4, 4, 8, 0])

In [26]:
# multiple condition
matrix_c[(matrix_c[:,:] % 2 == 0) & (matrix_c[:,:] <= 4)]

array([2, 0, 4, 4, 0])

## Dimensions and the Squeeze function

In [27]:
matrix_d =  np.array([[1,1,1,2,0], [3,6,6,7,4], [4,5,3,8,0]])
matrix_d

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [28]:
print(type(matrix_d).__name__)
print(type(matrix_d[0]))
print(type(matrix_d[0,0]))

ndarray
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [29]:
type(matrix_d[0,0:1])

numpy.ndarray

In [30]:
matrix_d[0:1,0:1].squeeze()

array(1)

In [31]:
print(matrix_d[0:1,0:1].squeeze())

1


In [32]:
type(matrix_d[0:1,0:1].squeeze())

numpy.ndarray

In [33]:
matrix_d[0:1,0:1].squeeze().ndim

0

In [34]:
matrix_d[0:1,0:1].squeeze().shape

()

In [35]:
np.squeeze(matrix_d[0:1,0:1])

array(1)

In [36]:
# o/p will be the same for syntax
print(matrix_d[0,0].squeeze().shape)
print(matrix_d[0,0:1].squeeze().shape)
print(matrix_d[0:1,0:1].squeeze().shape)

()
()
()


In [45]:
sq_matrix = np.squeeze(matrix_d)

2
